spring:
  datasource:
    primary:
      url: jdbc:mysql://localhost:3306/fieldmanager
      username: root
      password:
      driverClassName : com.mysql.jdbc.Driver
    secondary:
      url: jdbc:mysql://localhost:3306/idm
      username: root
      password:
      driverClassName : com.mysql.jdbc.Driver
server:
  port: 8082